Implemented NfcV Tag check
m2m-solutions/flutter-nfc-reader pull request #1
Opened 2024-08-21 13:34 UTC by henkeeman

Implemented a way to see if the nfc tag is NfcV (ISO 15693) or not on android devices.

This is becouse we want to reverse the array if its a NfcV tag to match it with how IOS handles it.

We dont want to reverse it if its NfcA for an example. Becouse android and IOS handles the reading the same.

2024-08-21 13:49 UTC, Edden01 requested changes

2024-08-21 13:49 UTC, Edden01 commented on android/src/main/kotlin/it/matteocrippa/flutternfcreader/NfcHandler.kt
> +        this.id.reversedArray().bytesToHexString()
change this.id to this.getId()

2024-08-22 08:22 UTC, henkeeman commented on android/src/main/kotlin/it/matteocrippa/flutternfcreader/NfcHandler.kt
> +        this.id.reversedArray().bytesToHexString()
Fixed :)

2024-08-22 08:30 UTC, Edden01 approved these changes

2024-08-22 08:30 UTC, merged